package eu.kanade.tachiyomi.extension.all.batotovx

import eu.kanade.tachiyomi.source.SourceFactory

class BatoToVxFactory : SourceFactory {
    override fun createSources() = listOf(
        BatoToVx("all", ""),
        BatoToVx("en"),
        BatoToVx("ar"),
        BatoToVx("bg"),
        BatoToVx("zh"),
        BatoToVx("cs"),
        BatoToVx("da"),
        BatoToVx("nl"),
        BatoToVx("fil"),
        BatoToVx("fi"),
        BatoToVx("fr"),
        BatoToVx("de"),
        BatoToVx("el"),
        BatoToVx("he"),
        BatoToVx("hi"),
        BatoToVx("hu"),
        BatoToVx("id"),
        BatoToVx("it"),
        BatoToVx("ja"),
        BatoToVx("ko"),
        BatoToVx("ms"),
        BatoToVx("pl"),
        BatoToVx("pt"),
        BatoToVx("pt-BR", "pt_br"),
        BatoToVx("ro"),
        BatoToVx("ru"),
        BatoToVx("es"),
        BatoToVx("es-419", "es_419"),
        BatoToVx("sv"),
        BatoToVx("tr"),
        BatoToVx("uk"),
        BatoToVx("vi"),
        BatoToVx("af"),
        BatoToVx("sq"),
        BatoToVx("am"),
        BatoToVx("hy"),
        BatoToVx("az"),
        BatoToVx("be"),
        BatoToVx("bn"),
        BatoToVx("bs"),
        BatoToVx("my"),
        BatoToVx("km"),
        BatoToVx("ca"),
        BatoToVx("ceb"),
        BatoToVx("zh-Hans", "zh_hk"),
        BatoToVx("zh-Hant", "zh_tw"),
        BatoToVx("hr"),
        BatoToVx("et"),
        BatoToVx("fo"),
        BatoToVx("ka"),
        BatoToVx("gn"),
        BatoToVx("gu"),
        BatoToVx("ht"),
        BatoToVx("ha"),
        BatoToVx("is"),
        BatoToVx("ig"),
        BatoToVx("ga"),
        BatoToVx("jv"),
        BatoToVx("kn"),
        BatoToVx("kk"),
        BatoToVx("ku"),
        BatoToVx("ky"),
        BatoToVx("lo"),
        BatoToVx("lv"),
        BatoToVx("lt"),
        BatoToVx("lb"),
        BatoToVx("mk"),
        BatoToVx("mg"),
        BatoToVx("ml"),
        BatoToVx("mt"),
        BatoToVx("mi"),
        BatoToVx("mr"),
        BatoToVx("mo"),
        BatoToVx("mn"),
        BatoToVx("ne"),
        BatoToVx("no"),
        BatoToVx("ny"),
        BatoToVx("ps"),
        BatoToVx("fa"),
        BatoToVx("rm"),
        BatoToVx("sm"),
        BatoToVx("sr"),
        BatoToVx("sh"),
        BatoToVx("st"),
        BatoToVx("sn"),
        BatoToVx("sd"),
        BatoToVx("si"),
        BatoToVx("sk"),
        BatoToVx("sl"),
        BatoToVx("so"),
        BatoToVx("sw"),
        BatoToVx("tg"),
        BatoToVx("ta"),
        BatoToVx("te"),
        BatoToVx("th"),
        BatoToVx("ti"),
        BatoToVx("to"),
        BatoToVx("tk"),
        BatoToVx("ur"),
        BatoToVx("uz"),
        BatoToVx("yo"),
        BatoToVx("zu"),
        BatoToVx("other", "_t"),
    )
}
